import { Routes } from '@angular/router';
import { HomeComponent } from './home.component';
import { HealthComponent } from './health.component';
import { ProjectsPageComponent } from './projects.page';
import { ProjectCreatePageComponent } from './project-create.page';
import { ProjectDetailPageComponent } from './project-detail.page';
import { ProjectMembersPageComponent } from './project-members.page';
import { TasksPageComponent } from './tasks.page';
import { ProjectTasksPageComponent } from './project-tasks.page';
import { BoardPageComponent } from './board.page';
import { ProjectBoardPageComponent } from './project-board.page';
import { NotificationsPageComponent } from './notifications.page';
import { TaskDetailPageComponent } from './task-detail.page';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'health', component: HealthComponent },
  { path: 'projects', component: ProjectsPageComponent },
  { path: 'projects/new', component: ProjectCreatePageComponent },
  { path: 'projects/:projectId', component: ProjectDetailPageComponent },
  { path: 'projects/:projectId/members', component: ProjectMembersPageComponent },
  { path: 'projects/:projectId/tasks', component: ProjectTasksPageComponent },
  { path: 'projects/:projectId/board', component: ProjectBoardPageComponent },
  { path: 'tasks', component: TasksPageComponent },
  { path: 'tasks/:taskId', component: TaskDetailPageComponent },
  { path: 'board', component: BoardPageComponent },
  { path: 'notifications', component: NotificationsPageComponent },
  { path: '**', redirectTo: '' }
];
