version: '3.9'
services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pmt_db}
      MYSQL_USER: ${MYSQL_USER:-pmt}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pmt}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_IMAGE_NAMESPACE:-local}/pmt-backend:dev
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-pmt_db}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-pmt}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-pmt}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_IMAGE_NAMESPACE:-local}/pmt-frontend:dev
    depends_on:
      - backend
    environment:
      API_BASE_URL: /api
    ports:
      - "4200:80"

volumes:
  db_data:
